#!/bin/bash
#SBATCH --job-name=gpt2-xl-fastdetect
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --mem=120G
#SBATCH --time=08:00:00
#SBATCH --array=0-1
#SBATCH --output=gpt2-xl-fastdetect-%A_%a.log

set -eo pipefail
module purge
module load 2025
module load Python/3.13.5-GCCcore-14.3.0
cd "$HOME/Multi-lingual-NLP"
source .venv/bin/activate

export HF_HOME="$HOME/hf_cache"
export HF_HUB_OFFLINE=1

datasets=(multisocial multitude)
dataset="${datasets[$SLURM_ARRAY_TASK_ID]}"

srun python -u score.py --detector fastdetect --dataset "$dataset" --scoring gpt2-xl \
    --output outputs/gpt2-xl
